# Generated by Django 2.0.1 on 2018-02-03 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workoutsets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('workoutset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actionsets', to='workoutsets.WorkoutSet')),
            ],
        ),
    ]
