# Generated by Django 2.0.1 on 2018-02-03 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workouts', '0001_initial'),
        ('workoutvideos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workoutsets', to='workoutvideos.WorkoutVideo')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workoutsets', to='workouts.Workout')),
            ],
        ),
    ]
